src/items/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from items.api import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.ItemListAPIView.as_view(), name='items'),
    # url(r'^add/$', views.add, name = 'add'),
    url(r'^(?P<pk>\d+)/$', views.ItemRetrieveAPIView.as_view(), name='item-detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/items/urls.py
from django.conf.urls import url
from django.contrib import admin
from items import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.items, name='items'),
    url(r'^add/$', views.add, name = 'add'),
    url(r'^(?P<id>\d+)/$', views.item_detail, name='detail'),
    url(r'^(?P<id>\d+)/buy$', views.buy, name='buy'),
    url(r'^(?P<id>\d+)/remove$', views.remove, name = 'remove'),
    url(r'^update_rating/$', views.update_rating, name = 'update_rating'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user_account/', include("user_account.urls", namespace="user_account")),
    url(r'^', include("items.urls", namespace="items")),
    url(r'^api/items/', include("items.api.urls", namespace="items-api")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_account/urls.py
from django.conf.urls import url
from django.contrib import admin
from user_account import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^login/', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register$', views.RegistrationFormView.as_view(), name='reg_home'),
    url(r'^$', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/items/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Item(models.Model):
	title = models.CharField(max_length=30)
	image = models.FileField(null=True, blank=True)
	description = models.TextField()
	brand = models.CharField(max_length=30, null=True)
	rating = models.FloatField(default=0)
	price = models.IntegerField(default=1000)
	users = models.ManyToManyField(User, related_name='users')
	sum_of_ratings = models.IntegerField(default=0)
	number_of_ratings = models.IntegerField(default=0)
	rated = models.ManyToManyField(User, related_name='users_rated')
	category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('items:detail', kwargs = {'id': self.id})

class Category(models.Model):
	title = models.CharField(max_length=50)

	def __unicode__(self):
		return self.title

src/items/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		widgets = {
          'description': forms.Textarea(attrs={'rows':20, 'cols':100}),
        }
		fields = ['title', 'category', 'brand', 'description', 'image', 'price']

src/items/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView
from items.models import Item
from .serializers import ItemSerializer

class ItemListAPIView(ListAPIView):
	queryset = Item.objects.all()
	serializer_class = ItemSerializer

class ItemRetrieveAPIView(RetrieveAPIView):
	queryset = Item.objects.all()
	serializer_class = ItemSerializer

src/items/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic import View
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.http import HttpResponseRedirect
from .models import Item, Category
from .forms import ItemForm
from django.views.decorators.csrf import csrf_exempt

def items(request):
    items = Item.objects.all()
    categories = Category.objects.all()
    search_query = request.GET.get("search_query")
    if search_query:
    	items = items.filter(title__icontains=search_query)
    context = {
    	"items": items,
    	"categories": categories
    }
    return render(request, 'items.html', context)
	
def add(request):
	form = ItemForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		form_instance = form.save(commit = False)
		form_instance.save()
		return HttpResponseRedirect(form_instance.get_absolute_url())

	context = {
		'form': form
	}
	if request.user.is_authenticated():
		return render(request, 'add_item.html', context)
	else:
		return render(request, 'items.html', context)

def remove(request, id):
	item = get_object_or_404(Item, id = id)
	item.delete()
	return redirect('items:items')

def item_detail(request, id):
	item = get_object_or_404(Item, id=id)
	items = Item.objects.all()
	search_query = request.GET.get("search_query")
	if search_query:
		items = items.filter(title__icontains=search_query)
		context = {
			"items": items
		}
		return render(request, 'items.html', context)
	rating = item.rating
	context = {
		'item': item,
		'title': item.title,
	}
	return render(request, 'item_detail.html', context)

def update_rating(request):
	if request.method == 'POST':
		item_id = request.POST['item_id']
		if 'rating' in request.POST:
			rating = request.POST['rating']
			items = Item.objects.all()
			for item in items:
				if item.id == int(item_id):
					if request.user in item.rated.all():
						return redirect('items:item_detail')
					if item.number_of_ratings == 0:
						obj = Item.objects.get(id=int(item_id))
						obj.rating = int(rating)
						obj.number_of_ratings += 1
						obj.sum_of_ratings += int(rating)
						obj.rated.add(request.user)
						obj.save()
					else:
						obj = Item.objects.get(id=int(item_id))
						obj.number_of_ratings += 1
						obj.sum_of_ratings += int(rating)
						avg_rating = obj.sum_of_ratings/float(obj.number_of_ratings)
						round(avg_rating, 1)
						obj.rating = avg_rating
						obj.rated.add(request.user)
						obj.save()
			return render(request, 'item_rating.html', {'rating': rating})

def buy(request, id):
	item = get_object_or_404(Item, id=id)
	item.users.add(request.user)
	context = {
		'user': request.user,
		'item': item,
		'title': item.title,
	}
	return render(request, 'item_detail.html', context)

src/templates/add_item.html
{% extends 'base.html' %}
{% block content %}
<h2>Items</h2>
{% if user.is_superuser %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add</button>
    </div>
</form>
{% endif %}
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>TheShop</title>
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://use.fontawesome.com/1c60a6053f.js"></script>
        <script src="https://tympanus.net/Tutorials/CaptionHoverEffects/js/modernizr.custom.js"></script>
        <script type="text/javascript">var URL = "{% url 'items:update_rating' %}";</script>

    </head>
    <body>
        <nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'user_account:index' %}">TheShop</a>
			</div>
			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class="nav navbar-nav pull-right">
					{% if user.is_superuser %}
						<li><a href="{% url 'items:add' %}">Add items</a></li>
					{% endif %}
					{% if not user.is_authenticated %}
					<li class=""><a href="{% url 'user_account:login' %}">Login</a></li>
                    <li class=""><a href="{% url 'user_account:reg_home' %}">Register</a></li>
					{% endif %}
					{% if user.is_authenticated %}
				        {% if user.first_name %}
							<li class=""><a href="">{{ user.first_name }} {{ user.last_name }}</a></li>
						{% else %}
							<li class=""><a href="">{{ user.username }}</a></li>
						{% endif %}
					<li class=""><a href="{% url 'user_account:logout' %}">Logout</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
        <script type="text/javascript">
		    $.fn.stars = function() {
		        return $(this).each(function() {
		            var val = parseFloat($(this).html());
		            var size = Math.max(0, (Math.min(5, val))) * 16;
		            var $span = $('<span />').width(size);
		            $(this).html($span);
		        });
		    }
		    $( document ).ready(function() {
		        $('span.stars').stars();
		    });
		</script>
    </body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

src/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-4">
	<div class="jumbotron text-center">
		<img src="{{ item.image.url }}" class="img-responsive" height="500" width="500">
	</div>
	<div class="jumbotron text-center">
		<p>Space for filters</p>
		<form method="GET">
			<input class="form-control" type="text" name="search_query" value="{{ request.GET.search_query }}" placeholder="Search Items"> <br>
			<input type="submit" name="" value="Search" class="btn btn-primary form-control">
		</form>
	</div>
</div>

<div class="col-md-8">
	<div class="jumbotron">
		<div class="container">
			<h2>{{ title }}</h2>
			<p>Rs. {{ item.price }} | <span class="stars" style="display:inline-block;">{{ item.rating }}</span></p>
			<a href="{{ item.get_absolute_url }}buy" class="btn btn-success">Buy</a>
			{% if user in item.users.all %}
				{% if user not in item.rated.all %}
					<button class="btn btn-warning" data-toggle="modal" data-target="#myModal">Rate</button>
				{% endif %}
			{% endif %}
			{% if user.is_superuser %}
				<a href="{{ item.get_absolute_url }}remove" class="btn btn-danger">Remove</a>
			{% endif %}
			<h3>Description</h3>
			<p>{{ item.description }}</p>
		</div>
	</div>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Rate {{ item.title }}</h4>
			</div>
			<div class="modal-body">
				<section class='rating-widget'>
					<div class='rating-stars text-center'>
						<ul id='stars'>
						<li class='star' title='Poor' data-value='1'>
							<i class='fa fa-star fa-fw'></i>
						</li>
						<li class='star' title='Fair' data-value='2'>
							<i class='fa fa-star fa-fw'></i>
						</li>
						<li class='star' title='Good' data-value='3'>
							<i class='fa fa-star fa-fw'></i>
						</li>
						<li class='star' title='Excellent' data-value='4'>
							<i class='fa fa-star fa-fw'></i>
						</li>
						<li class='star' title='Outstanding' data-value='5'>
							<i class='fa fa-star fa-fw'></i>
						</li>
						</ul>
					</div>
				</section>
			</div>
			<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
      
    </div>
  </div>
<script type="text/javascript">
	$(document).ready(function(){
		$('#stars li').on('mouseover', function(){
	    	var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on
	   
	    // Now highlight all the stars that's not after the current hovered star
	    	$(this).parent().children('li.star').each(function(e){
	      		if (e < onStar) {
	        		$(this).addClass('hover');
	      		}
		      	else {
		        	$(this).removeClass('hover');
		      	}
	    	});
	  	}).on('mouseout', function(){
	    	$(this).parent().children('li.star').each(function(e){
	      		$(this).removeClass('hover');
			});
	  	});
	  
		$('#stars li').on('click', function(){
			var onStar = parseInt($(this).data('value'), 10); // The star currently selected
			var stars = $(this).parent().children('li.star');

			for (i = 0; i < stars.length; i++) {
				$(stars[i]).removeClass('selected');
			}

			for (i = 0; i < onStar; i++) {
				$(stars[i]).addClass('selected');
			}

			var ratingValue = parseInt($('#stars li.selected').last().data('value'), 10);
			var data = {'rating': ratingValue, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'item_id': '{{ item.id }}'}
			$.post(URL, data, function(response) {});
	  	});
	});
</script>

{% endblock %}

src/templates/item_rating.html
{% extends 'base.html' %}
{% block content %}
{{rating}}
{% endblock %}

src/templates/items.html
{% extends 'base.html' %}
{% block content %}
<div class="col-xs-12">
	<div class="jumbotron jmb-main">
		<div class="col-xs-12 text-center">
			<h1>
				Amazing deals this Diwali
				<br>
				<span class="lead">Shop now at <strong>TheShop</strong> for amazing discounts.</span>
			</h1>
		</div>
	</div>
</div>
<div class="col-xs-3">
	<div class="jumbotron jmb text-center">
		<p>Space for filters</p>
		<form method="GET">
			<input class="form-control" type="text" name="search_query" value="{{ request.GET.search_query }}" placeholder="Search Items"> <br>
			<input type="submit" name="" value="Search" class="btn btn-primary form-control">
		</form>
	</div>
</div>

<div class="col-xs-9">
	{% for c in categories %}
	<div class="jumbotron jmb">
		<div class="container">
		<h3>{{ c.title }}s</h3>
		{% for item in items %}
			{% if item.category.title == c.title %}
				<div class="col-md-4">
					<div class="thumbnail">
						<br>
						<a href="{{ item.get_absolute_url }}"><img src="{{ item.image.url }}"></a>
						<div class="caption text-center">
							<h3>{{ item.title }}</h3> by <b>{{ item.brand }}</b>
							<p>Rs. {{ item.price }} | <span class="stars" style="display:inline-block;">{{ item.rating }}</span></p>
							<a class="btn btn-success">Buy</a> <a class="btn btn-warning" href="{{ item.get_absolute_url }}">Details</a>
						</div>
					</div>
				</div>
			{% endif %}
		{% endfor %}
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

src/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h2>Login</h2>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

src/templates/reg_home.html
{% extends 'base.html' %}
{% block content %}

<h2>Register</h2>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
</form>
{% endblock %}